### ISSUE TITLE
Not urls returned for stationary periods:

### ISSUE THREAD

**Issue by Rafnuss** [grhyne/SWWA_Pressure#7]
@grhyne : 
After fixing the pressure outlier points with CB620, I am now getting an error (see below) when querying the pressure map (1-pressure) that says the ERA5 data is not available for the final stationary period, i.e. the latest dates recorded. This is unusual, because I have already made 15 other pressure maps from periods after this and in the same geographic extent. Testing this error, I tried to run a tag that is already finished, and was given the same error, meaning it is something to do with the ERA5 database most likely. Are you also receiving these errors? The assumption is that it will be resolved when the data is available soon, but like I said, I have already queried during this time period with no problems before.

```
> pressure_maps <- geopressure_map(pam_short$pressure,
+   extent = c(gpr$extent_N, gpr$extent_W, gpr$extent_S, gpr$extent_E),
+   scale = gpr$map_scale,
+   max_sample = gpr$map_max_sample,
+   margin = gpr$map_margin
+ )

Generate requests:
Requests generated successfully for 0 stationary periods ()

Send requests:
[==================================================] 1 / 1
Download geotiff:
[                                                  ] 0 / 1 Error during the reading of the file. We return the urls of the gee request, the filename to the file already downloaded and the pressure_maps already computed. Here is the original error:
Could not resolve host: NAWarning message:
In geopressure_map(pam_short$pressure, extent = c(gpr$extent_N,  :
Not urls returned for stationary periods: 12. It is probably due to request(s) made for periods where no data are available. Note that ERA5 data is usually only available on GEE ~3-5 months after.
```

**Comment by Rafnuss** [comment]
fixed in https://github.com/Rafnuss/GeoPressureR/commit/680af6e6b9203e12386e43de6ad5533bc77d5b8c

**Comment by grhyne** [comment]
The request goes through now, thank you. It still does not generate URLs for the final stationary periods of all tags I run (which are the recapture sites, so it is not very important), but still odd given this only recently started happening, and I did not have a problem with it prior to two days ago

**Comment by Rafnuss** [comment]
Yes, we've noticed that the code wasn't provided an error message if data is missing. So, do you still have a problem with it? What is the recovery date/last date available?

**Comment by grhyne** [comment]
@Rafnuss The problem has now completely gone away, it is now generating data for the final stationary period. I did not change anything since working on it Friday, so there must have been an update in the URL database for those late recordings (~May - June 2022)
